// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8KwZKUeZHjVeQQHaGSY1pt2KIb7Shz0w',
    appId: '1:656171184137:web:3cace8ad8deed80a2ac8d8',
    messagingSenderId: '656171184137',
    projectId: 'yogaproject-258da',
    authDomain: 'yogaproject-258da.firebaseapp.com',
    storageBucket: 'yogaproject-258da.firebasestorage.app',
    measurementId: 'G-DEGFE67GK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtUrht2pMm1Mcgf5PHQCcyUkvKwVHDFCQ',
    appId: '1:656171184137:android:ff19b103f2cd17672ac8d8',
    messagingSenderId: '656171184137',
    projectId: 'yogaproject-258da',
    storageBucket: 'yogaproject-258da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOLqUr7RALotJWBP7SyNkFh_YgNjhHnOI',
    appId: '1:656171184137:ios:c633d48f18ffd4c02ac8d8',
    messagingSenderId: '656171184137',
    projectId: 'yogaproject-258da',
    storageBucket: 'yogaproject-258da.firebasestorage.app',
    iosBundleId: 'com.example.frontEnd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOLqUr7RALotJWBP7SyNkFh_YgNjhHnOI',
    appId: '1:656171184137:ios:c633d48f18ffd4c02ac8d8',
    messagingSenderId: '656171184137',
    projectId: 'yogaproject-258da',
    storageBucket: 'yogaproject-258da.firebasestorage.app',
    iosBundleId: 'com.example.frontEnd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8KwZKUeZHjVeQQHaGSY1pt2KIb7Shz0w',
    appId: '1:656171184137:web:33cb3f08b546e9382ac8d8',
    messagingSenderId: '656171184137',
    projectId: 'yogaproject-258da',
    authDomain: 'yogaproject-258da.firebaseapp.com',
    storageBucket: 'yogaproject-258da.firebasestorage.app',
    measurementId: 'G-7R4FHRJN6E',
  );
}
